channels:
  - conda-forge
dependencies:
  - python=3.8.3
  - r-base=3.6.3
  - rpy2=3.3.3
  # Python dependencies
  - pip
  - pip:
    - -r file:setup/requirements.txt
  # R dependencies
  - r-ggplot2=3.3.2
  - r-patchwork=1.1.0
